Underscore in number literal
google/vim-ft-go pull request #7
Opened 2021-03-28 15:21 UTC by 89z

Fix #6

2021-03-28 18:16 UTC, dbarnett requested changes
Thanks! Suggested one tweak. 👍 apart from that.

2021-03-28 18:16 UTC, dbarnett commented on syntax/go.vim
> +syn match       goDecimalInt        "\<[0-9_]\+\([Ee]\d\+\)\?\>"
You don't want this to match leading underscores like `_42` though, right? That's an identifier per https://golang.org/ref/spec#Integer_literals. Probably want to change that part of the pattern to `[1-9][0-9_]*`.

2021-03-28 19:22 UTC, 89z commented
I tried this:

~~~
\<[1-9][0-9_]*\+\([Ee]\d\+\)\?\>
~~~

but I get:

~~~
E871: (NFA regexp) Can't have a multi follow a multi
~~~

I dont know what the hell that means. I am pretty good with RegEx, but not Vim RegEx.

2021-03-28 19:26 UTC, 89z commented
Updated to deal with starting underscore

2021-03-28 20:48 UTC, dbarnett approved these changes
Thanks! Merging...

2021-03-28 20:49 UTC, merged

2021-03-29 13:26 UTC, 89z commented
Hey @dbarnett why did you say `1-9`? Now plain `0` doesnt get highlighted

2021-03-29 16:29 UTC, dbarnett commented
> Hey @dbarnett why did you say `1-9`? Now plain `0` doesnt get highlighted

Ah, good catch. I was following the structure of the `decimal_lit` spec at https://golang.org/ref/spec#Integer_literals, but I guess forgot to include the part for 0 itself (`"0" | …`). I should really get some tests added…

Thanks for catching and fixing in #8!